services:
  - type: web
    name: checkmate-acevector
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
